### ISSUE TITLE
Could not find openrave_catkin

### ISSUE THREAD

**Issue by wonchul-kim** [crigroup/robotiq#2]
while i did catkin_make to compile your code...

I got error about ' could not find openrave_catkin"

how can i install it???

I find that you have the source of openrave_catkin in your git.
However, I don't understand to install it...... 

Could you help me?

Also, i attached it to UR3 and add the controller by the below:
  <rosparam file="$(find robotiq_control)/config/cmodel_action_controller.yaml" command="load"/>
  <node name="gripper_controller_spawner" pkg="controller_manager" type="spawner" args="gripper --shutdown-timeout 0.5" />

Is this right???

**Comment by fsuarez6** [comment]
@wonchul-kim no need for so many question marks. One is more than enough, don't you agree?
To 'install' `openrave_catkin`, just clone that repo into your catkin workspace:
```bash
cd ~/catkin_ws/src
git clone https://github.com/crigroup/openrave_catkin
```

**Comment by fsuarez6** [comment]
On a second thought, the easiest workaround would be to modify [robotiq_description/CMakeLists.txt](https://github.com/crigroup/robotiq/blob/7c67910f2fdc306604821015c4ff900f7d633799/robotiq_description/CMakeLists.txt).
Remove lines 14,13 and 5.

**Comment by wonchul-kim** [comment]
Thank you for your reply!

I already did all what you said.

First, I downloaded openrave_catkin in your git and did catkin_make, but I
got this error :
CMake Error at openrave_catkin-master/CMakeLists.txt:5 (find_package):
  By not providing "FindOpenRAVE.cmake" in CMAKE_MODULE_PATH this project
has
  asked CMake to find a package configuration file provided by "OpenRAVE",
  but CMake did not find one.

  Could not find a package configuration file provided by "OpenRAVE" with
any
  of the following names:

    OpenRAVEConfig.cmake
    openrave-config.cmake

  Add the installation prefix of "OpenRAVE" to CMAKE_PREFIX_PATH or set
  "OpenRAVE_DIR" to a directory containing one of the above files.  If
  "OpenRAVE" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
See also "/home/icsl/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/icsl/catkin_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed


Secondly, i edited CMakeLists.txt as you said. I removed lines 13, 14 and
replace openrave_catkin to roslaunch.
Then, i succeeded to complete catkin_make.
However, when I controlled the gripper, I got error....

I think i spawned the gripper in a wrong way....

This is how i attached the gripper to the UR3 manipulator.
in launch file,
  <rosparam file="$(find
robotiq_control)/config/cmodel_action_controller.yaml" command="load"/>
  <node name="gripper_controller_spawner" pkg="controller_manager"
type="spawner" respawn="false" output="screen" />

in xacro file,

  <xacro:include filename="$(find
robotiq_description)/urdf/robotiq_85_gripper.urdf.xacro" />
  <xacro:robotiq_85_gripper prefix="" parent="tool0" >
    <origin xyz="0.0 0.0 -0.01" rpy="1.57 -1.57 0"/>
  </xacro:robotiq_85_gripper>

then, when i launched the gazebo  this error came up:
[gripper_controller-10] process has died [pid 1501, exit code 2, cmd
/opt/ros/kinetic/lib/controller_manager/spawner __name:=gripper_controller
__log:=/home/icsl/.ros/log/de353384-8313-11e7-8c7e-a0c58912381f/gripper_controller-10.log].
log file:
/home/icsl/.ros/log/de353384-8313-11e7-8c7e-a0c58912381f/gripper_controller-10*.log



and the below is came up when i tried to roslaunch robotiq_control
cmodel_simple_controller.launch

r: Reset
a: Activate
c: Close
o: Open
(0-255): Go to that position
f: Faster
l: Slower
i: Increase force
d: Decrease force
-->Traceback (most recent call last):
  File
"/home/icsl/catkin_ws/src/robotiq-master/robotiq_control/scripts/cmodel_tcp_driver.py",
line 41, in <module>
    mainLoop(sys.argv[1])
  File
"/home/icsl/catkin_ws/src/robotiq-master/robotiq_control/scripts/cmodel_tcp_driver.py",
line 22, in mainLoop
    status = gripper.getStatus()
  File
"/home/icsl/catkin_ws/src/robotiq-master/robotiq_control/src/robotiq_control/cmodel_base.py",
line 112, in getStatus
    status = self.client.getStatus(6);
  File
"/home/icsl/catkin_ws/src/robotiq-master/robotiq_control/src/robotiq_control/cmodel_base.py",
line 51, in getStatus
    response = self.client.read_input_registers(0, numRegs)
  File "/usr/lib/python2.7/dist-packages/pymodbus/client/common.py", line
120, in read_input_registers
    return self.execute(request)
  File "/usr/lib/python2.7/dist-packages/pymodbus/client/sync.py", line 82,
in execute
    raise ConnectionException("Failed to connect[%s]" % (self.__str__()))
pymodbus.exceptions.ConnectionException: Modbus Error: [Connection] Failed
to connect[192.168.0.13:502]
[cmodel_tcp_driver-1] process has died [pid 2611, exit code 1, cmd
/home/icsl/catkin_ws/src/robotiq-master/robotiq_control/scripts/cmodel_tcp_driver.py
192.168.0.13 __name:=cmodel_tcp_driver
__log:=/home/icsl/.ros/log/de353384-8313-11e7-8c7e-a0c58912381f/cmodel_tcp_driver-1.log].
log file:
/home/icsl/.ros/log/de353384-8313-11e7-8c7e-a0c58912381f/cmodel_tcp_driver-1*.log




Could you please help me?

2017-08-17 15:09 GMT+09:00 Francisco <notifications@github.com>:

**Comment by fsuarez6** [comment]
That problem doesn't have anything to do with the URDF.
The driver is unable to connect to your gripper.

What is the IP address of your gripper?
I guess it's not `192.168.0.13`.

**Comment by wonchul-kim** [comment]
I am just doing simulation by gazebo.
in gazebo, is there IP address of gripper?

What I really want to ask is if I edited launch and xacro file to atttach the gripper to the UR3 manipulator as I showed in the right above question. 

This is how i attached the gripper to the UR3 manipulator. in launch file,

<rosparam file="$(find robotiq_control)/config/cmodel_action_controller.yaml" command="load"/> 
<node name="gripper_controller_spawner" pkg="controller_manager" type="spawner" respawn="false" output="screen" />

in xacro file,

<xacro:include filename="$(find robotiq_description)/urdf/robotiq_85_gripper.urdf.xacro" /> <xacro:robotiq_85_gripper prefix="" parent="tool0" >
 <origin xyz="0.0 0.0 -0.01" rpy="1.57 -1.57 0"/>
 </xacro:robotiq_85_gripper>

then, when i launched the gazebo this error came up: 
[gripper_controller-10] process has died [pid 1501, exit code 2, cmd /opt/ros/kinetic/lib/controller_manager/spawner __name:=gripper_controller __log:=/home/icsl/.ros/log/de353384-8313-11e7-8c7e-a0c58912381f/gripper_controller-10.log]. log file: /home/icsl/.ros/log/de353384-8313-11e7-8c7e-a0c58912381f/gripper_controller-10*.log

**Comment by fsuarez6** [comment]
Oh, I see.
[Here](https://github.com/quangounet/osr_course_pkgs/blob/ed23833a6f1fcdc7d1b40d0b319ba52f923be988/osr_description/urdf/denso_robotiq_85_gripper.urdf.xacro#L48) you can find a working example.
That robot is shown [here](http://osrobotics.org/pages/robot_simulation.html), figure 2.

**Comment by wonchul-kim** [comment]
Thank you!!!

Final question, what is cmodel?
I've seen in robotiq official github that there are cmodel and just normal
model.

what is the difference?



2017-08-17 16:46 GMT+09:00 Francisco <notifications@github.com>:

**Comment by fsuarez6** [comment]
No clue

**Comment by LKuik** [comment]
@ wonchul-kim what do you mean by 'replace openrave_catkin to roslaunch, when you said:

> Secondly, i edited CMakeLists.txt as you said. I removed lines 13, 14 and
> replace openrave_catkin to roslaunch.

I have the same problem with `catkin_make`

**Comment by LKuik** [comment]
Instead of removing line 5 from robotiq_description/CMakeLists.txt, I removed line 5 from  openrave_catkin/CMakeLists.txt . 
With this I was able to `catkin_make ` succesfully
