### ISSUE TITLE
Upgrade robotiq_gazebo to Melodic (gazebo 9)

### ISSUE THREAD

**Issue by felixvd** [crigroup/robotiq#4]
I am in the middle of upgrading our system to Melodic, but sadly `robotiq_gazebo` does not compile with Gazebo 9.

These are the build errors:
```
Errors     << robotiq_gazebo:make /root/catkin_ws/logs/robotiq_gazebo/build.make.000.log             
/root/catkin_ws/src/robotiq/robotiq_gazebo/src/mimic_joint_plugin.cpp: In destructor 'virtual gazebo::MimicJointPlugin::~MimicJointPlugin()':
/root/catkin_ws/src/robotiq/robotiq_gazebo/src/mimic_joint_plugin.cpp:50:18: error: 'DisconnectWorldUpdateBegin' is not a member of 'gazebo::event::Events'
   event::Events::DisconnectWorldUpdateBegin(this->updateConnection);
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~
/root/catkin_ws/src/robotiq/robotiq_gazebo/src/mimic_joint_plugin.cpp: In member function 'void gazebo::MimicJointPlugin::UpdateChild()':
/root/catkin_ws/src/robotiq/robotiq_gazebo/src/mimic_joint_plugin.cpp:170:39: error: 'class gazebo::physics::World' has no member named 'GetPhysicsEngine'; did you mean 'SetPhysicsEnabled'?
   static ros::Duration period(world_->GetPhysicsEngine()->GetMaxStepSize());
                                       ^~~~~~~~~~~~~~~~
                                       SetPhysicsEnabled
/root/catkin_ws/src/robotiq/robotiq_gazebo/src/mimic_joint_plugin.cpp:173:26: error: 'class gazebo::physics::Joint' has no member named 'GetAngle'; did you mean 'GetForce'?
   double angle = joint_->GetAngle(0).Radian()*multiplier_+offset_;
                          ^~~~~~~~
                          GetForce
/root/catkin_ws/src/robotiq/robotiq_gazebo/src/mimic_joint_plugin.cpp:175:30: error: 'class gazebo::physics::Joint' has no member named 'GetAngle'; did you mean 'GetForce'?
   if(abs(angle-mimic_joint_->GetAngle(0).Radian())>=sensitiveness_)
                              ^~~~~~~~
                              GetForce
/root/catkin_ws/src/robotiq/robotiq_gazebo/src/mimic_joint_plugin.cpp:179:32: error: 'class gazebo::physics::Joint' has no member named 'GetAngle'; did you mean 'GetForce'?
       double a = mimic_joint_->GetAngle(0).Radian();
                                ^~~~~~~~
                                GetForce
/root/catkin_ws/src/robotiq/robotiq_gazebo/src/mimic_joint_plugin.cpp:183:31: error: 'gazebo::math' has not been declared
       double effort = gazebo::math::clamp(pid_.computeCommand(error, period), -max_effort_, max_effort_);
                               ^~~~
make[2]: *** [CMakeFiles/gazebo_mimic_joint_plugin.dir/src/mimic_joint_plugin.cpp.o] Error 1
make[1]: *** [CMakeFiles/gazebo_mimic_joint_plugin.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 2
```

The [migration notes](https://bitbucket.org/osrf/gazebo/src/default/Migration.md?fileviewer=file-view-default) mention most of these.

**Comment by rlunding** [comment]
The newest version from https://github.com/roboticsgroup/roboticsgroup_gazebo_plugins seems to work.

**Comment by Raouf-sawas** [comment]
@felixvd hi, I had the same problem, you can fix it by replacing  the folowing:

-   event::Events::DisconnectWorldUpdateBegin(this->updateConnection); 
    to
+  this->updateConnection.reset();

- GetPhysicsEngine()->
   to
+ Physics()

- GetAngle(0).Radian();
  to 
+ Position ( 0 )

- gazebo::math::clamp
  to
+ ignition::math::clamp

it should work fine

**Comment by felixvd** [comment]
@ABDULRaouf92 Thanks. I think you should actually make that a PR :)

**Comment by HoraN1** [comment]
`/home/horace/catkin_ws/src/gazebo_ros_link_attacher/src/gazebo_ros_link_attacher.cpp: In member function ‘bool gazebo::GazeboRosLinkAttacher::attach(std::__cxx11::string, std::__cxx11::string, std::__cxx11::string, std::__cxx11::string)’:
/home/horace/catkin_ws/src/gazebo_ros_link_attacher/src/gazebo_ros_link_attacher.cpp:66:40: error: ‘class gazebo::physics::World’ has no member named ‘GetByName’; did you mean ‘BaseByName’?
     physics::BasePtr b1 = this->world->GetByName(model1);
                                        ^~~~~~~~~
                                        BaseByName
/home/horace/catkin_ws/src/gazebo_ros_link_attacher/src/gazebo_ros_link_attacher.cpp:72:40: error: ‘class gazebo::physics::World’ has no member named ‘GetByName’; did you mean ‘BaseByName’?
     physics::BasePtr b2 = this->world->GetByName(model2);
                                        ^~~~~~~~~
                                        BaseByName
In file included from /opt/ros/melodic/include/ros/ros.h:40:0,
                 from /home/horace/catkin_ws/src/gazebo_ros_link_attacher/src/gazebo_ros_link_attacher.cpp:2:
/home/horace/catkin_ws/src/gazebo_ros_link_attacher/src/gazebo_ros_link_attacher.cpp:94:100: error: ‘class gazebo::physics::Inertial’ has no member named ‘GetMass’; did you mean ‘SetMass’?
  inertia is not NULL, for example, mass is: " << l1->GetInertial()->GetMass());
                                                                     ^
/opt/ros/melodic/include/ros/console.h:358:64: note: in definition of macro ‘ROSCONSOLE_PRINT_STREAM_AT_LOCATION_WITH_FILTER’
     __rosconsole_print_stream_at_location_with_filter__ss__ << args; \
                                                                ^~~~
/opt/ros/melodic/include/ros/console.h:406:7: note: in expansion of macro ‘ROSCONSOLE_PRINT_STREAM_AT_LOCATION’
       ROSCONSOLE_PRINT_STREAM_AT_LOCATION(args); \
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/ros/melodic/include/ros/console.h:579:43: note: in expansion of macro ‘ROS_LOG_STREAM_COND’
 #define ROS_LOG_STREAM(level, name, args) ROS_LOG_STREAM_COND(true, level, name, args)
                                           ^~~~~~~~~~~~~~~~~~~
/opt/ros/melodic/include/rosconsole/macros_generated.h:59:32: note: in expansion of macro ‘ROS_LOG_STREAM’
 #define ROS_DEBUG_STREAM(args) ROS_LOG_STREAM(::ros::console::levels::Debug, ROSCONSOLE_DEFAULT_NAME, args)
                                ^~~~~~~~~~~~~~
/home/horace/catkin_ws/src/gazebo_ros_link_attacher/src/gazebo_ros_link_attacher.cpp:94:9: note: in expansion of macro ‘ROS_DEBUG_STREAM’
         ROS_DEBUG_STREAM("link1 inertia is not NULL, for example, mass is: " << l1->GetInertial()->GetMass());
         ^
/home/horace/catkin_ws/src/gazebo_ros_link_attacher/src/gazebo_ros_link_attacher.cpp:106:100: error: ‘class gazebo::physics::Inertial’ has no member named ‘GetMass’; did you mean ‘SetMass’?
  inertia is not NULL, for example, mass is: " << l2->GetInertial()->GetMass());
                                                                     ^
/opt/ros/melodic/include/ros/console.h:358:64: note: in definition of macro ‘ROSCONSOLE_PRINT_STREAM_AT_LOCATION_WITH_FILTER’
     __rosconsole_print_stream_at_location_with_filter__ss__ << args; \
                                                                ^~~~
/opt/ros/melodic/include/ros/console.h:406:7: note: in expansion of macro ‘ROSCONSOLE_PRINT_STREAM_AT_LOCATION’
       ROSCONSOLE_PRINT_STREAM_AT_LOCATION(args); \
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/ros/melodic/include/ros/console.h:579:43: note: in expansion of macro ‘ROS_LOG_STREAM_COND’
 #define ROS_LOG_STREAM(level, name, args) ROS_LOG_STREAM_COND(true, level, name, args)
                                           ^~~~~~~~~~~~~~~~~~~
/opt/ros/melodic/include/rosconsole/macros_generated.h:59:32: note: in expansion of macro ‘ROS_LOG_STREAM’
 #define ROS_DEBUG_STREAM(args) ROS_LOG_STREAM(::ros::console::levels::Debug, ROSCONSOLE_DEFAULT_NAME, args)
                                ^~~~~~~~~~~~~~
/home/horace/catkin_ws/src/gazebo_ros_link_attacher/src/gazebo_ros_link_attacher.cpp:106:9: note: in expansion of macro ‘ROS_DEBUG_STREAM’
         ROS_DEBUG_STREAM("link2 inertia is not NULL, for example, mass is: " << l2->GetInertial()->GetMass());
         ^
/home/horace/catkin_ws/src/gazebo_ros_link_attacher/src/gazebo_ros_link_attacher.cpp:118:27: error: ‘math’ has not been declared
     j.joint->Load(l1, l2, math::Pose());
                           ^~~~
/home/horace/catkin_ws/src/gazebo_ros_link_attacher/src/gazebo_ros_link_attacher.cpp:136:14: error: ‘class gazebo::physics::Joint’ has no member named ‘SetHighStop’
     j.joint->SetHighStop(0, 0);
              ^~~~~~~~~~~
/home/horace/catkin_ws/src/gazebo_ros_link_attacher/src/gazebo_ros_link_attacher.cpp:138:14: error: ‘class gazebo::physics::Joint’ has no member named ‘SetLowStop’; did you mean ‘SetPosition’?
     j.joint->SetLowStop(0, 0);
              ^~~~~~~~~~
              SetPosition
gazebo_ros_link_attacher/CMakeFiles/gazebo_ros_link_attacher.dir/build.make:62: recipe for target 'gazebo_ros_link_attacher/CMakeFiles/gazebo_ros_link_attacher.dir/src/gazebo_ros_link_attacher.cpp.o' failed
make[2]: *** [gazebo_ros_link_attacher/CMakeFiles/gazebo_ros_link_attacher.dir/src/gazebo_ros_link_attacher.cpp.o] Error 1
CMakeFiles/Makefile2:3703: recipe for target 'gazebo_ros_link_attacher/CMakeFiles/gazebo_ros_link_attacher.dir/all' failed
make[1]: *** [gazebo_ros_link_attacher/CMakeFiles/gazebo_ros_link_attacher.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by murtazabasu** [comment]
@ABDULRaouf92  I still get this error after making the following changes which you specified

```
/home/murtaza/catkin_ws/src/robotiq/robotiq_gazebo/src/mimic_joint_plugin.cpp: In destructor ‘virtual gazebo::MimicJointPlugin::~MimicJointPlugin()’:
/home/murtaza/catkin_ws/src/robotiq/robotiq_gazebo/src/mimic_joint_plugin.cpp:50:19: error: ‘DisconnectWorldUpdateBegin’ is not a member of ‘gazebo::event::Events’
    event::Events::DisconnectWorldUpdateBegin(this->updateConnection.reset());
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
robotiq/robotiq_gazebo/CMakeFiles/gazebo_mimic_joint_plugin.dir/build.make:62: recipe for target 'robotiq/robotiq_gazebo/CMakeFiles/gazebo_mimic_joint_plugin.dir/src/mimic_joint_plugin.cpp.o' failed
make[2]: *** [robotiq/robotiq_gazebo/CMakeFiles/gazebo_mimic_joint_plugin.dir/src/mimic_joint_plugin.cpp.o] Error 1
CMakeFiles/Makefile2:4325: recipe for target 'robotiq/robotiq_gazebo/CMakeFiles/gazebo_mimic_joint_plugin.dir/all' failed
make[1]: *** [robotiq/robotiq_gazebo/CMakeFiles/gazebo_mimic_joint_plugin.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j12 -l12" failed 
```
The other errors seems to be solved

**Comment by Raouf-sawas** [comment]
@Murtaza786-oss 
you should also replace this line " event::Events::DisconnectWorldUpdateBegin(this->updateConnection.reset());"  
with" this->updateConnection.reset();"
then it should work

**Comment by nlimpert** [comment]
@ABDULRaouf92 thanks for your notes on how to upgrade to Gazebo 9 - works for me too.

I'll add myself to those who'd appreciate a PR for this. :wink:

**Comment by filesmuggler** [comment]
@ABDULRaouf92 it compiles, thank you!

**Comment by nicholasadr** [comment]
I have added the suggested changes in a new branch `melodic-devel` to support Gazebo 9. Thank you everyone especially @ABDULRaouf92. I will close this issue.

**Comment by qq44642754a** [comment]
> @felixvd hi, I had the same problem, you can fix it by replacing the folowing:
> 
> * event::Events::DisconnectWorldUpdateBegin(this->updateConnection);
>   to
> 
> * this->updateConnection.reset();
> 
> * GetPhysicsEngine()->
>   to
> 
> * Physics()
> 
> * GetAngle(0).Radian();
>   to
> 
> * Position ( 0 )
> 
> * gazebo::math::clamp
>   to
> 
> * ignition::math::clamp
> 
> it should work fine

love U bro!

**Comment by abdulmuqeet23661** [comment]
I am trying to lauch ur5 with gripper in Moveit. When I run the command as followed, 

 roslaunch ur5_picknplace vew_gripper_arm.launch  
 
 it shows me that 
 
 RLException: [vew_gripper_arm.launch] is neither a launch file in package [ur5_picknplace] nor is [ur5_picknplace] a launch file name
The traceback for the exception was written to the log file

What should I do now so it may work with the gripper?
