### ISSUE TITLE
How to connect to ur5 robot

### ISSUE THREAD

**Issue by LKuik** [crigroup/robotiq#6]
Hi, I have cloned & build the package for the gripper. Now I want to control the robotiq gripper that is attached to the ur5 robot. Can I control it with :
`roslaunch robotiq_control cmodel_simple_controller.launch ip:=ROBOTIQ_IP_ADDRESS`
with the IP adress from the robot. 
Because I tried, but nothing happens. What should I do to make the ur5 + robotiq gripper controllable with ROS?

**Comment by felixvd** [comment]
The ROBOTIQ_IP_ADDRESS is the address of the dedicated robotiq controller: 

<img width="505" alt="Screen Shot 2019-05-23 at 11 53 44" src="https://user-images.githubusercontent.com/4535737/58267368-7a593380-7d51-11e9-806f-d1ff0295ff11.png">

If you use a UR, use the `roslaunch robotiq_control cmodel_simple_controller.launch topic:=YOUR_URSCRIPT_TOPIC_NAME` instead. Replace the topic name with your own, obviously. It's the one where the UR package receives URScript messages, probably `/your_robot/URScript`.

**Comment by LKuik** [comment]
Thank you!

**Comment by felixvd** [comment]
If this solved the issue, please close it.
